name: app_serviceflow

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  signature: ^5.4.0

  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true